#import <Cocoa/Cocoa.h>
#import <ScriptingBridge/ScriptingBridge.h>

// these are autogenerated
#import "Chrome.h" // sdef /Applications/Google\ Chrome.app | sdp -fh --basename Chrome
#import "Safari.h" // sdef /Applications/Safari.app | sdp -fh --basename Safari
#import "Mail.h" // sdef /Applications/Mail.app | sdp -fh --basename Mail

@interface CurrentApplicationChecker : NSObject {
  NSManagedObjectContext *managedObjectContext;
}

- (id)initWithManagedObjectContext:(NSManagedObjectContext *)context;

@end
